# Generated by Django 5.1.dev20240313164637 on 2024-05-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=13)),
                ('image', models.ImageField(upload_to='book_images/')),
                ('publication_year', models.IntegerField()),
                ('publisher', models.CharField(max_length=50)),
                ('pages', models.IntegerField()),
                ('dimensions', models.CharField(max_length=50)),
                ('cover_type', models.CharField(choices=[('soft', 'Softcover'), ('hard', 'Hardcover')], max_length=4)),
                ('category', models.CharField(choices=[('romance', 'Romance'), ('thriller', 'Thriller'), ('biography', 'Biography'), ('classic', 'Classic'), ('drama', 'Drama'), ('history', 'History')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('founded_year', models.IntegerField()),
                ('website', models.URLField()),
            ],
        ),
    ]
